version: "3.9"
services:
  backend:
    build: ./backend
    environment:
      - APP_ENV=development
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - DATA_DIR=/data
      - SERVE_STATIC=false
      - CORS_ORIGINS=http://localhost:5173
      - MAX_UPLOAD_MB=25
    volumes:
      - backend_data:/data
      - ./backend/app:/app/app
    ports:
      - "8000:8000"

  web:
    image: node:20
    working_dir: /web
    volumes:
      - ./web:/web
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:8000

volumes:
  backend_data: 